### ISSUE TITLE
-> trigger bug?

### ISSUE THREAD

**Issue by mihaelartz** [marlonfan/coc-phpls#10]
I have problem with -> trigger

e.g.
```php
<?php
$pdo = new PDO('');

$pdo-> // no completions
$pdo-> // i must start typing something for get a completions for some class

// This problem not appear in vscode
// ccls for C++ have -> trigger and works fine

```
Sorry for my bad English. Thanks!

**Comment by marlonfan** [comment]
Can I see ``CocInfo`` and ``LSP output``?

**Comment by mihaelartz** [comment]
@marlonfan https://gist.github.com/mihaelartz/79fb7abc2a2be302bfa0ab1012e8222e

**Comment by mihaelartz** [comment]
![2019-04-15-123707_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/56126325-38331a00-5f7b-11e9-8af1-e3af37d4707f.png)
![2019-04-15-123711_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/56126326-38331a00-5f7b-11e9-9a19-8608e2678729.png)

**Comment by marlonfan** [comment]
Check your ``coc`` and ``coc-phpls`` version  or try minimum environmental?  No LSP incomplete is triggered when you enter a '>'?'.

But he's normal on my machine

My LSP Log:
```plain
[Trace - 7:06:03 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 62,
        "uri": "file:///Users/marlon/Dev/code/php/swoole-channel/test.php"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 4,
                    "character": 5
                },
                "end": {
                    "line": 4,
                    "character": 5
                }
            },
            "rangeLength": 0,
            "text": ">"
        }
    ]
}


[Trace - 7:06:03 PM] Sending request 'textDocument/completion - (20)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/marlon/Dev/code/php/swoole-channel/test.php"
    },
    "position": {
        "line": 4,
        "character": 6
    },
    "context": {
        "triggerKind": 2,
        "triggerCharacter": ">"
    }
}
```

Desktop:
![image](https://user-images.githubusercontent.com/9349370/56128678-f45c0700-5fb2-11e9-8da2-1b523d149ec6.png)

**Comment by mihaelartz** [comment]
@marlonfan Yep, problem is closetag plugin...
