### ISSUE TITLE
Enums support

### ISSUE THREAD

**Issue by BrayanCaro** [marlonfan/coc-phpls#114]
**Describe the bug**
A simple enum definition throws:
```
foo.php:3 [intelephense 1001] Error Unexpected 'Name'. Expected ';'.
foo.php:4 [intelephense 1001] Error Unexpected 'case'.
```

**To Reproduce**
Create a file `foo.php` with:
```php
<?php

enum Status
{
    case DRAFT;
    case PUBLISHED;
    case ARCHIVED;
}
```

**Expected behavior**
No errors excepted.

**Screenshots**
![image](https://user-images.githubusercontent.com/41640423/186504346-982bcb0e-c2d3-4423-8cf3-bd4c567f3e9f.png)

**Desktop**
 - OS: Ubuntu 22.04.1 LTS
 - coc-phpls: 2.2.2

**Comment by axmad386** [comment]
any workaround for this? may be just how to suspress the errors warning

**Comment by BrayanCaro** [comment]
That solves the issue, thank you so much!
