### ISSUE TITLE
Upgrade intelephense to v1.9

### ISSUE THREAD

**Issue by rtucek** [marlonfan/coc-phpls#119]
Thank you for maintaining this awesome package!

Right now, the underlying intelephense language server is pinned towards version `~1.8`. However, with the beginning of 2023, the intelephense maintainer [released v1.9](https://github.com/bmewburn/vscode-intelephense/blob/master/CHANGELOG.md). Most importantly, it comes with PHP v8.2 support.

Would you mind upgrade intelephense to v1.9?

**Comment by marlonfan** [comment]
Ok, I will upgrade today @rtucek

**Comment by lewissteele** [comment]
@marlonfan Hi, I've raised a PR to upgrade intelephense to 1.9 if you could please take a look at it: https://github.com/marlonfan/coc-phpls/pull/120 Thanks :smile: 

I've been using it with my vim and it works perfectly :partying_face:

**Comment by marlonfan** [comment]
@lewissteele Just now, the new version upgrade was completed

**Comment by stefanos82** [comment]
Can you upgrade it to the latest version? There's a bug with stubs and has been fixed a while ago; it cannot recognize builtin functions such as `rand()` and such.
