### ISSUE TITLE
duplication in hover show docs and autocompletion

### ISSUE THREAD

**Issue by kalloc** [marlonfan/coc-phpls#23]
**Describe the bug**
Duplication in all information that showed from `coc-phpls`

**nvim config:**
```vim
"" PHP
call coc#add_extension('coc-phpls')
let g:coc_filetypes += ['php']
```

**coc-settings.json:**
```json
{
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "objc", "objcpp"],
      "rootPatterns": [
        ".ccls",
        "compile_commands.json",
        ".vim/",
        ".git/",
        ".hg/"
      ],
      "initializationOptions": {
        "cacheDirectory": "/tmp/ccls"
      }
    },
    "intelephense": {
      "command": "intelephense",
      "args": ["--stdio"],
      "filetypes": ["php"],
      "initializationOptions": {
        "storagePath": "/tmp/intelephense"
      }
    }
  }
}
```

**To Reproduce**
1. Install coc
2. Install coc-phpls
3. Install intelephense (`npm i intelephense -g`)
4. try to autocomplete and/or show docs

**Screenshots**

<img width="786" alt="image" src="https://user-images.githubusercontent.com/177687/58108795-233e4c00-7bf5-11e9-83fd-21b7d036c95c.png">

**Desktop (please complete the following information):**
 - nvim 0.4.0
 - Mac OS X
- coc.nvim version: 0.0.67
- intelephense 1.0.14

**Additional context**
`coc-go`, `coc-rls`, and `coc-python` works well.

**Comment by marlonfan** [comment]
remove “intelephense” will done


发自我的iPhone

------------------ Original ------------------

**Comment by marlonfan** [comment]
You need remove "intelephense" in language server config 


发自我的iPhone

------------------ Original ------------------

**Comment by kalloc** [comment]
@marlonfan it helped

**Comment by marlonfan** [comment]
No, it's not a good idea


------------------ Original ------------------

**Comment by kalloc** [comment]
@marlonfan coc-phpls install intelephense to `$HOME/.config/coc/extensions/node_modules/intelephense/`

**Comment by marlonfan** [comment]
“Intelephense" and "coc-phpls" will start two server on same time.  Either one will do

**Comment by kalloc** [comment]
thanks
