### ISSUE TITLE
Configure PHP warnings/errors

### ISSUE THREAD

**Issue by robbash** [marlonfan/coc-phpls#25]
Hi.

Not sure if I'm right here but I feel like I need to start somewhere: I installed this extension to enable coc for PHP files. Due to the nature of the project, there are a few _unused private static_ properties in the classes. Is there a way, to configure what to warn or show errors about?

Thanks in advance, appreciate the effort you take.

**Comment by marlonfan** [comment]
This is a bug, I will check the cause and fix it as soon as possible

**Comment by mihaelartz** [comment]
@marlonfan This is not bug. For now, can't be reproduced.

@robbash Intelephense use own static analysis engine, and does not offer any option for solve your problem, for now. - Try this option, disable coc diagnostic, use ale, neomake or something else instead coc diagnostic, use PHPStan, allows you to configure, see https://github.com/phpstan/phpstan

### Part of my coc-config
``
{
    "coc.preferences.diagnostic.enable": false
}
``
### Part of my ale configuration
```vim
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_enter = 0
let g:ale_linters = {
    \ 'php': ['phpstan']
    \ }
```

Sorry for my bad English! I hope I helped :)

**Comment by marlonfan** [comment]
@mihaelartz I understand,in my opinion, that intelphine is an LSP, but it does not implement this aspect of the feature.

**Comment by robbash** [comment]
Thanks, @mihaelartz.

Have the diagnostics disabled now, so all these warnings that were annoying me disappeared. Haven't managed to get ale/phpstan running yet but will work on that.

**Comment by mihaelartz** [comment]
@robbash
1. Install PHPStan with composer: ```composer global require --dev phpstan/phpstan```
2. If you want configure PHPStan, create new file in your project root with name ```phpstan.neon.dist``` and put your configuration in that file. (OPTIONAL)

And that's it :)

**Comment by robbash** [comment]
@mihaelartz thanks a lot. It's checking the files now. Cheers!

**Comment by yaegassy** [comment]
@marlonfan @robbash @m5ome

`phpstan` is now supported in `coc-diagnostic`.

https://github.com/iamcco/coc-diagnostic
