### ISSUE TITLE
Intelephense Premium

### ISSUE THREAD

**Issue by danielpieper** [marlonfan/coc-phpls#29]
Thank you for this extension! I bought intelephense premium to support the author. 
Does it make sense to add the licence key like `intelephense.licenceKey` to the configuration?

**Comment by rodrigore** [comment]
Hi, I recently noticed that intelephense has nice premium features.  They work with coc ?

**Comment by marlonfan** [comment]
I will check the related feature for follow-up

**Comment by fabiosal** [comment]
bmewburn/intelephense-docs#12 might help

**Comment by marlonfan** [comment]
New version released, It's supported now
