### ISSUE TITLE
find implementations feature

### ISSUE THREAD

**Issue by fabiosal** [marlonfan/coc-phpls#33]
i'm using coc.nvim with coc-phpls and when i'm trying to use the **find implementation** feature on a interface symbol using

`nmap <silent> gi <Plug>(coc-implementation)`

I receive this message

> [coc.nvim] Error on 'jumpImplementation': Cannot read property 'start' of undefined

**Comment by marlonfan** [comment]
This is a known problem. Is to repair

**Comment by marlonfan** [comment]
@fabiosal upgrade to 2.1.2.   current is available. but will get a error message: (intermediate value) is not iterable, in solving...

**Comment by fabiosal** [comment]
@marlonfan It seems that works, it finds extensions and implementations. I let you know if I find something broken
