### ISSUE TITLE
这个插件是要开始收费了吗？

### ISSUE THREAD

**Issue by Anoxia** [marlonfan/coc-phpls#35]
这几天插件工作不正常，过来看文档之后发现有会员特性了，作者这是要开始收费了吗？

**Comment by marlonfan** [comment]
额.. 不会的 目前正常维护没有收费 你看到的收费功能是这个语言服务器上层增加了一些支持, 同时增加了一个专业版的选择.

具体工作不正常指的是什么呢？我可以看下.

**Comment by Anoxia** [comment]
感谢回复，是我自己配置异步加载启动 Coc.nvim 有问题，导致这个插件未正常工作。

期待专业版，你实现的这个 LSP 实在是太好用了，我要成为你的第一批付费用户以表示我的喜爱。
