### ISSUE TITLE
Configurable auto phpdoc creation

### ISSUE THREAD

**Issue by derekhamilton** [marlonfan/coc-phpls#38]
A feature of intelephense is "Configurable auto phpdoc creation that infers return types and identifies thrown exceptions." Is there a way to call this via coc.nvim?

**Comment by AlexandreHagen** [comment]
Up ?

**Comment by AlexandreHagen** [comment]
https://github.com/neoclide/coc.nvim/issues/590

**Comment by derekhamilton** [comment]
That is just talking about autocompletion. "auto phpdoc creation" is about generating phpdoc blocks for methods, with things like `@throws` for any exceptions that are unhandled.

**Comment by AlexandreHagen** [comment]
You right. I also looked for any code about Phpdoc in coc-phpls. I found nothing. So isn’t currently support I guess. Now the only solution is to implement it ourselves.

**Comment by tofulm** [comment]
there is : 
https://github.com/kkoomen/vim-doge

**Comment by AlexandreHagen** [comment]
Thanks @tofulm I didn’t know it.

**Comment by yaegassy** [comment]
In the current version of "intelephense", the generation of phpdocs is possible from code actions.

It is available in coc-phpls using the CodeAction feature. `<Plug>(coc-codeaction)`

You will need to purchase an intelephense license and have it set to intelephense.licenceKey.

**Ref:** https://github.com/bmewburn/vscode-intelephense/commit/c4423153254acf5267df9bd6508c7f44e4995902

```
- Add PHPDoc code action (in addition to existing **Premium**
```

**Demo**

![coc-phpls-gen-phpdoc](https://user-images.githubusercontent.com/188642/87884647-aa31c300-ca4a-11ea-8f17-17e71b2cfd87.gif)

**Comment by derekhamilton** [comment]
Thank you! For any other onlookers, if intelephense is not up-to-date, you'll get an error `coc.nvim: CodeAction not found` when calling `<Plug>coc-codeaction`.
