### ISSUE TITLE
Any way to add stubs for Wordpress?

### ISSUE THREAD

**Issue by willdavidow** [marlonfan/coc-phpls#39]
I'm having a little difficulty figuring out whether or not there's a way to add stubs for Wordpress development? 

I noticed this repository mentioned in an issue in the intelephense repo: https://github.com/php-stubs/wordpress-stubs but I'm having trouble figuring out whether or not it's possible to somehow include this in my COC configuration to prevent/stop intelephense errors on Wordpress built-in functions.

<img width="532" alt="Screen Shot 2019-12-08 at 10 00 40 PM" src="https://user-images.githubusercontent.com/763985/70403929-549e2e00-1a06-11ea-8c68-5ec4fdf9c9da.png">

**Comment by willdavidow** [comment]
I'm not 100% sure how definitions and sources are gathered by LSP's but this appears to be working just fine now without any configuration change on my end. 

<img width="665" alt="Screen Shot 2019-12-12 at 11 59 10 AM" src="https://user-images.githubusercontent.com/763985/70732655-d75d0c80-1cd6-11ea-9004-e155bb2a02dc.png">

Closing this for now since my question appears to have resolved itself.

**Comment by wanecek** [comment]
FWIW: I stumbled across the same issue. One solution is to get the raw `wordpress-stubs.php`-file from https://github.com/GiacoCorsiglia/wordpress-stubs, and put it anywhere in the project directory. Intelliphense will pick it up when indexing, and this will stub the methods. When doing so, one may want to include it in your (global) gitignore as well.
