### ISSUE TITLE
Problem in accepting completion

### ISSUE THREAD

**Issue by mihaelartz** [marlonfan/coc-phpls#4]
Hey!

I have a problem, when accept variable completion i get e.g.
```php
$number = 5;

echo // when accept $number completion i get, $$number, but it should be $number
```

Sorry for my bad English. Thanks!

**Comment by marlonfan** [comment]
@mihaelartz add to your ``.vimrc`` file:

```vim
autocmd FileType php setl iskeyword+=$
```

detail:
- [#1](https://github.com/marlonfan/coc-phpls/issues/1)
- [#2](https://github.com/StanAngeloff/php.vim/issues/88)

**Comment by mihaelartz** [comment]
@marlonfan Thanks!
