### ISSUE TITLE
内存泄漏 风扇不停转

### ISSUE THREAD

**Issue by webmrsong** [marlonfan/coc-phpls#43]
## versions

vim version: NVIM v0.4.3
node version: v13.5.0
coc.nvim version: 0.0.74-cd348f4905
term: iTerm.app
platform: darwin

## Messages
[coc.nvim] Your Intelephense licence key has been activated.
[phpls] Undefined function 'main\array_slice'. [E]

[phpls] Undefined function 'main\array_slice'. [E]
[phpls] Undefined function 'main\array_slice'. [E]
[phpls] Undefined function 'main\array_slice'. [E]
[phpls] Undefined function 'main\array_slice'. [E]
## Output channel: phpls

[Info  - 6:43:12 PM] Initialising intelephense 1.3.6
[Info  - 6:43:12 PM] Reading state from /Users/mrsong/.config/coc/extensions/coc-phpls-data/3c2c6bd6.
[Info  - 6:43:13 PM] Initialised in 972 ms
[Info  - 6:43:13 PM] Intelephense 1.2.3

<--- Last few GCs --->

[13253:0x104900000]    84371 ms: Mark-sweep 1950.8 (2067.2) -> 1937.2 (2063.9) MB, 618.9 / 0.0 ms  (average mu = 0.243, current mu = 0.198) allocation failure scavenge might not succeed
[13253:0x104900000]    84429 ms: Scavenge 1951.1 (2063.9) -> 1938.8 (2065.4) MB, 5.0 / 0.0 ms  (average mu = 0.243, current mu = 0.198) allocation failure 
[13253:0x104900000]    84481 ms: Scavenge 1952.8 (2065.4) -> 1940.5 (2066.9) MB, 4.1 / 0.0 ms  (average mu = 0.243, current mu = 0.198) allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x10074e5f9]
Security context: 0x1ee16f440921 <JSObject>
    1: split [0x1ee16f44d1a1](this=0x1ee172550159 <String[432]: Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/Frameworks/Steam Helper.app/Contents/Frameworks/HTML5App.app/Contents/Frameworks/Steam Helper EH.app/Contents/Frameworks/Steam Helper.app/Contents/Frameworks/Steam Helper EH.app/Contents/Frameworks/HTML5App.app/Contents/Frameworks/Ste...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100b9f982 node::Abort() (.cold.1) [/usr/local/Cellar/node/13.5.0/bin/node]
 2: 0x100084338 node::FatalError(char const*, char const*) [/usr/local/Cellar/node/13.5.0/bin/node]
 3: 0x100084460 node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node/13.5.0/bin/node]
 4: 0x10017dfc1 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/13.5.0/bin/node]
 5: 0x10017df6b v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/13.5.0/bin/node]
 6: 0x100297f23 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/Cellar/node/13.5.0/bin/node]
 7: 0x1002992a8 v8::internal::Heap::MarkCompactPrologue() [/usr/local/Cellar/node/13.5.0/bin/node]
 8: 0x100296e76 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/Cellar/node/13.5.0/bin/node]
 9: 0x100295955 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/Cellar/node/13.5.0/bin/node]
10: 0x10029d2f4 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/13.5.0/bin/node]
11: 0x10029d34a v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/13.5.0/bin/node]
12: 0x10027a04a v8::internal::Factory::New(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationType) [/usr/local/Cellar/node/13.5.0/bin/node]
13: 0x10027d9f1 v8::internal::Factory::NewProperSubString(v8::internal::Handle<v8::internal::String>, int, int) [/usr/local/Cellar/node/13.5.0/bin/node]
14: 0x100501e73 v8::internal::Runtime_StringSplit(int, unsigned long*, v8::internal::Isolate*) [/usr/local/Cellar/node/13.5.0/bin/node]
15: 0x10074e5f9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/Cellar/node/13.5.0/bin/node]
16: 0x10073c402 Builtins_StringPrototypeSplit [/usr/local/Cellar/node/13.5.0/bin/node]
[Info  - 6:44:37 PM] Connection to server got closed. Server will restart.
[Info  - 6:44:37 PM] Initialising intelephense 1.3.6
[Info  - 6:44:37 PM] Reading state from /Users/mrsong/.config/coc/extensions/coc-phpls-data/3c2c6bd6.
[Info  - 6:44:37 PM] Initialised in 9 ms

**Comment by marlonfan** [comment]
我跟进下上游   最近在996没注意到╯□╰

**Comment by webmrsong** [comment]
好的  非常感谢

**Comment by webmrsong** [comment]
> 我跟进下上游 最近在996没注意到╯□╰
好的  非常感谢

**Comment by marlonfan** [comment]
@webmrsong 升级下最新版本  看有改善么
