### ISSUE TITLE
Index on workspace change

### ISSUE THREAD

**Issue by mihaelartz** [marlonfan/coc-phpls#5]
Hey!

I have a new problem, when I'm in vim and install php package with composer i must to restart vim, or restart language server with CocRestart for index package, but the problem is that every time everything is over indexing... It would be nice if this were resolved and some one added caching system. Thanks!

Again sorry for my very bad English... :D

**Comment by marlonfan** [comment]
Yes, that's on the plan

The ability of this project to provide prompts depends on [vscode-intelephense](https://github.com/bmewburn/vscode-intelephense)

But the project closes the source code

I'm trying to fit this

**Comment by marlonfan** [comment]
The new version will be cached
