### ISSUE TITLE
 Cannot find module 'tslib'

### ISSUE THREAD

**Issue by zdmgmail** [marlonfan/coc-phpls#64]
**Describe the bug**

[coc.nvim]Error on load extension coc-phpls from /home/zdm/.config/coc/extensions/node_modules/coc-phpls/l
ib/index.js: Error: Cannot find module 'tslib'
Require stack:
- /home/zdm/.config/coc/extensions/node_modules/coc-phpls/lib/index.js
- /home/zdm/.config/coc/extensions/node_modules/coc-phpls/lib/index.js

**Desktop (please complete the following information):**

uname -a     
```                                           
Linux ar 5.6.14-arch1-1 #1 SMP PREEMPT Wed, 20 May 2020 20:43:19 +0000 x86_64 GNU/Linux
```     

 nvim --version                                          
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Additional context**

I install tslib with pacman -S tslib but still have this problem

**Comment by marlonfan** [comment]
Does reinstallation solve your problem?

**Comment by zdmgmail** [comment]
> Does reinstallation solve your problem?
> 
> I guess some of the dependencies may not have been installed properly

yes
