### ISSUE TITLE
Add Use Statement in Normal Mode

### ISSUE THREAD

**Issue by cxgslegend** [marlonfan/coc-phpls#68]
Sorry if this is obvious, but is there a way to add the use statement for a class in normal mode? Currently, I have to go to the class go into insert mode, delete a few characters, then start adding them back in to trigger the completion window. Then from there, I can pick correct class, and it will add the Use statement at the top. 

It would be nice if I could just hover over the class, and use a key mapping to add the use statement. I thought, maybe I could use `<Plug>(coc-fix-current)`, but guess that doesn't do what I thought it did. 

Thanks

**Comment by yaegassy** [comment]
This feature is available on the recently updated `intelephense` 1.5.1.

----

**Intelephense changelog**

- Import symbol code action **[Premium](https://intelephense.com)**
    - https://github.com/bmewburn/vscode-intelephense/commit/c4423153254acf5267df9bd6508c7f44e4995902

----

It is available in coc-phpls using the CodeAction feature. `<Plug>(coc-codeaction)`

You will need to purchase an intelephense license and have it set to `intelephense.licenceKey`.

**Demo**

![use_codeaction](https://user-images.githubusercontent.com/188642/87273319-b9c57f00-c513-11ea-9554-6edc45fef20e.gif)

**Comment by cxgslegend** [comment]
Thank you @yaegassy. Do you know how I get the latest intelephense version? I am pretty sure coc-phpls installed it for me. 

Or should I just wait for the project authors to update the project?

**Comment by cxgslegend** [comment]
I figured out that if I went into the ~/.config/coc/extensions directory and updated npm, I would get the updated version of intelephense. However, I still don't see anything when I try to run the `<Plug>(coc-codeaction)`. I get an error that says I need a function name. 

<img width="681" alt="Screen Shot 2020-07-13 at 12 05 53 PM" src="https://user-images.githubusercontent.com/8932713/87327785-88908300-c502-11ea-8de5-81a0c8039712.png">

**Comment by yaegassy** [comment]
@cxgslegend 

I think there may be a misconfiguration of the `<Plug>(coc-codeaction)` mapping.

Here's an example configuration.

```vim
nmap <silent> ga <Plug>(coc-codeaction)
```

Alternatively, you can directly execute the actual function to be executed by `<Plug>(coc-codeaction)`.

```
:call CocActionAsync('codeAction','')
```

I have prepared a DEMO so that you can understand the keyboard input as well, so please refer to it.

I tried it on vim8 and there is a slight difference in the display on nvim.

**DEMO(vim8)**

![coc-phpls-vim8-codaction_960](https://user-images.githubusercontent.com/188642/87364289-46248000-c5ae-11ea-8f0f-3001f30f17ec.gif)

**Snapshot(nvim)**

<img width="1247" alt="coc-phpls-nvim-codaction" src="https://user-images.githubusercontent.com/188642/87364335-648a7b80-c5ae-11ea-8832-a2430bbcc047.png">

**Comment by yaegassy** [comment]
@cxgslegend How to use the latest intelephense in coc-phpls.

I created this Pull Request. https://github.com/marlonfan/coc-phpls/pull/67

Once this is merged, you will certainly have the latest version of the current intelephense available.

Alternatively, you may be able to use the latest version of intelephense by uninstalling and reinstalling coc-phpls once.

```
:CocUninstall coc-phpls
:CocInstall coc-phpls
```

**Comment by cxgslegend** [comment]
Thank you @yaegassy. I am using [vim-which-key](https://github.com/liuchengxu/vim-which-key) for my mappings. So I guess I misconfigured it or something. When I deleted it and tried again, it worked (maybe there was something wrong with the dictionary structure). 

This is how it looks now:
```
let g:which_key_map.l = {
\'name' : '+lsp' ,
\	'.' : [':CocConfig'                          , 'config'],
\	'a' : ['<Plug>(coc-codeaction)'              , 'code action'],
\	'd' : ['<Plug>(coc-definition)'              , 'definition'],
\	'f' : ['<Plug>(coc-format-selected)'         , 'format selected'],
\	'i' : ['<Plug>(coc-implementation)'          , 'implementation'],
\	'm' : [':CocList diagnostics'                , 'diagnostics messages'],
\	'n' : ['<Plug>(coc-diagnostic-next-error)'   , 'next error'],
\	'p' : ['<Plug>(coc-diagnostic-prev-error)'   , 'prev error'],
\	'e' : ['<Plug>(coc-rename)'                  , 'edit name (rename)'],
\	'r' : ['<Plug>(coc-references)'              , 'references'],
\	's' : [':CocList -I symbols'                 , 'search symbols'],
\	't' : ['<Plug>(coc-type-definition)'         , 'type definition'],
\}
```
Regardless, its working now. Thank you so much. Sorry if this was too trivial. I really appreciated it.

<img width="689" alt="Screen Shot 2020-07-13 at 8 04 09 PM" src="https://user-images.githubusercontent.com/8932713/87365656-c910f080-c544-11ea-9b04-2ca3c60da36f.png">

**Comment by yaegassy** [comment]
@cxgslegend I'm glad it worked. Happy viming!
