### ISSUE TITLE
EISDIR error & max file size

### ISSUE THREAD

**Issue by tomspeak** [marlonfan/coc-phpls#7]
Hey,

I am trying to get this working in a small laravel project, but `:CocInfo` gives me these errors:

```
## versions

vim version: NVIM v0.3.4
node version: v10.9.0
coc.nvim version: 0.0.64
term: tmux-256color
platform: darwin

## Error messages

## Output channel: watchman
[Info  - 23:04:28] watchman watching project: /Users/t/Sites/test
[Info  - 23:04:29] subscribing "**/*.php" in /Users/t/Sites/test

## Output channel: highlight
[Info  - 23:04:28] Highlight server running in node v10.9.0

## Output channel: php
[Info  - 23:04:29] Initialising
[Info  - 23:04:30] Initialised in 357 ms
[Warn  - 23:04:49] EISDIR: illegal operation on a directory, read
[Warn  - 23:05:06] file:///Users/t/Sites/test/vendor/fzaninotto/faker/src/Faker/Provider/nl_BE/Text.php exceeds max file size.
```

I ran `:CocInstall coc-phpls` and set `autocmd FileType php setl iskeyword+=$`.

Is there something I am doing wrong? Cheers

**Comment by marlonfan** [comment]
Because ``Faker`` provide a large mock file, I will add a ``ignore file list`` option fix this problem.

Thanks

**Comment by tomspeak** [comment]
I was wondering if you had any advice on configuring it for a Laravel project? It seems to not be able to auto-complete or provide help with many parts of developing a Laravel app.

**Comment by marlonfan** [comment]
It is recommended that you use [laravel_ide_helper](https://github.com/barryvdh/laravel-ide-helper), which is also applicable to LSP

**Comment by tomspeak** [comment]
Strange, I have done that and added all of the generated files, but still it cannot auto complete

`User::find()`, or any framework related things, only my own hand written functions.

**Comment by marlonfan** [comment]
I just tried it with laravel. Maybe can vim's workspace and LSP cache be checked?

Helper method:
![image](https://user-images.githubusercontent.com/9349370/55501881-f6060080-567d-11e9-85f2-e642ede90a4b.png)

Model:
![image](https://user-images.githubusercontent.com/9349370/55502045-4aa97b80-567e-11e9-9910-442c9fac4c9c.png)

**Comment by tomspeak** [comment]
So strange, I have nuked my workspace, regenerated via artisan commands, re-loaded everything.

`:CocInfo` spits out

```
## Output channel: php
[Info  - 19:20:30] Initialising
[Info  - 19:20:31] Initialised in 355 ms
[Warn  - 19:20:44] EISDIR: illegal operation on a directory, read
[Warn  - 19:20:54] file:///Users/t/Sites/indebtandlove-laravel/vendor/fzaninotto/faker/src/Faker/Provider/nl_BE/Text.php exceeds max file size.
[Warn  - 19:21:31] EISDIR: illegal operation on a directory, read
[Warn  - 19:21:37] file:///Users/t/Sites/indebtandlove-laravel/vendor/fzaninotto/faker/src/Faker/Provider/nl_BE/Text.php exceeds max file size.
```

![Screenshot 2019-04-03 at 7 21 01 pm](https://user-images.githubusercontent.com/2415569/55503242-32b60580-5646-11e9-814b-e0aa7c66327f.png)
![Screenshot 2019-04-03 at 7 21 12 pm](https://user-images.githubusercontent.com/2415569/55503250-35185f80-5646-11e9-90df-51886306ea3e.png)

**Comment by marlonfan** [comment]
You can use open verbose log to see, perhaps because trigger word problem?

1. add ``phpls.trace.server`` to your coc-config
2. use CocCommand open log [CocCommand workspace. showOutput](https://github.com/neoclide/coc.nvim/wiki/Debug-language-server)

**Comment by tomspeak** [comment]
https://gist.github.com/tomspeak/638211dd5b0bd117212982706d02609a - Can you see anything wrong in the output?

There's 250,000 other lines, but I cannot see any explicit errors.

Would you mind sharing your vimrc / coc config?

**Comment by marlonfan** [comment]
Sure, here is my repo: [vimrc](https://github.com/marlonfan/vimrc)

**Comment by tomspeak** [comment]
How strange. I cannot see anything that would be different between our settings. Will keep investigating, I really do not want to use PHPStorm!

**Comment by marlonfan** [comment]
Can I see your version of intelephense-server?  because the new version has many updates, it may not be compatible? my version is 0.8.6

**Comment by tomspeak** [comment]
I am using `npm install intelephense@1.0.10 -g` — unless you meant something different? That's all I have installed.

**Comment by marlonfan** [comment]
Please downgrade the use, they are not compatible

**Comment by marlonfan** [comment]
Just released a new version, maybe you can try to solve the problem?

**Comment by tomspeak** [comment]
Strangely after upgrading it is now completely broken:

```
Error: Cannot find module '/Users/t/.config/coc/extensions/node_modules/coc-phpls/node_modules/intelephense/lib/intelephense.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
[Info  - 21:02:28] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:583
    throw err;
    ^
```

**Comment by marlonfan** [comment]
NPM package install error, please uninstall the old version first

**Comment by jonleopard** [comment]
Not sure if this was the right thing to do, but what worked for me was cd'ing into the coc-phpls directory, and running `yarn upgrade-interactive --latest`.


```
$ cd .config/coc/extensions/node_modules/coc-phpls
$ yarn upgrade-interactive --latest
```

Perhaps the dependencies need to be updated for the project? I can push a PR if you'd like @marlonfan ?

**Comment by marlonfan** [comment]
@jonleopard  Sure, thanks so much

**Comment by marlonfan** [comment]
@jonleopard Sure, thanks so much

**Comment by jonleopard** [comment]
Done :) 

https://github.com/marlonfan/coc-phpls/pull/8

**Comment by jonleopard** [comment]
Everything seems to be working for me so far, but I did not test thoroughly @marlonfan. 

@tomspeak `coc.vim` _should_ update `coc-phpls` automatically when you start vim. But if it doesn't, `:CocUpdate` should do the trick.

**Comment by marlonfan** [comment]
Thank you very much. I will test it.

**Comment by jonleopard** [comment]
Hmm, well I may have spoken too soon. I'm getting this error again:

```
Error: Cannot find module '/Users/jon/.config/coc/extensions/node_modules/coc-phpls/node_modules/intelephense/lib/intelephense.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[Info  - 10:24:59 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:584
    throw err;
    ^
```

I wonder if there is some sort of caching issue...

**Comment by marlonfan** [comment]
@jonleopard I fixed it.

**Comment by jonleopard** [comment]
@marlonfan Works great now, thanks!

**Comment by marlonfan** [comment]
@tomspeak Yes, ignoring some file feature will be released in 2.0.4.

**Comment by tomspeak** [comment]
Other than that warning everything is working extremely well. I don’t feel like I need to load PhpStorm so much. 

I was wondering if you could share some workflow tips? Unfortunately with Laravel go to definition never seems to work for me, but searching for the symbol is flawless. I’m trying to get the most out of CoC! But I’m not sure what I’m missing out on.

**Comment by marlonfan** [comment]
#20 v2.0.5 released.

Now support add exclude file list and max file lines
