### ISSUE TITLE
Is there a way to list and use particular Intelephense actions (commands)?

### ISSUE THREAD

**Issue by welblaud** [marlonfan/coc-phpls#76]
Intelephense works as expected but I somehow can't figure out how to use some of its other functions (commands), e.g., how to use symbol renaming in vim (it is one of the premium features). In VS, it is simply bound to F2 or a menu item. I guess I should be able to create my own mappings but I don't know how to invoke the command per se (if possible). (Coc has already accepted the license key.)

**Comment by jaghaimo** [comment]
Command is `coc-rename`, this will bind it to Alt + r:
```
nmap <A-r> <Plug>(coc-rename)
```

**Comment by welblaud** [comment]
Thanks, works like a charm. Closing. It would also be great to include this in the docs.  In addition, it would be nice to know about other coc-* commands but I guess it could be buried somewhere in the docs for coc itself.
