### ISSUE TITLE
Phpls premium features are not working as expected

### ISSUE THREAD

**Issue by mohammedabdoh** [marlonfan/coc-phpls#86]
**Describe the bug**
When I try to find all implementations of interface/abstract class within a project that was just indexed everything works. If I close neovim and open it again nothing works until I run the command `intelephense.index.workspace`. I made sure that I have no global intelephense module installed on my machine to avoid any conflicts. The current up to date version of intelephense is 1.5.4 while coc-phpls is using 1.5.2 (which I assume is installed with the extension as a dependency) so only the dependency that comes with the extension is available. I also tried it while there is a global module installed and I have the same issue. I have a premium subscription to make sure every premium feature is available. Note that the premium subscription works when using visual studio code.

**To Reproduce**
1. Open a php project for indexing for the first time.
2. Try to find all implementations of any interface or abstract class you can see that you will get a list of all of them.
3. Close nvim.
4. Open nvim again and open any php interface again then try to find implementations again you will receive a message `[coc.nvim] implementation not found`

**Expected behavior**
To be able to see all the implementations and the premium features working as expected

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Coc.nvim (the latest version)
 - Coc-phpls extension (the latest version)

**Additional context**
My CocInfo

```
[Info  - 11:48:19 AM] Initialising intelephense 1.5.2
[Info  - 11:48:19 AM] Reading state from /Users/fox/.config/coc/extensions/coc-phpls-data/56b54f92.
[Info  - 11:48:20 AM] Initialised in 1051 ms
```

**Comment by ivaaaan** [comment]
I'm having the same issue

**Comment by mohammedabdoh** [comment]
> licence

Man thank you so much you saved me.

**Comment by tomaspavlatka** [comment]
I still do have this issue. I use VIM 8.2 and still cannot see any implemantation even after creating the file mentioned here. 

thanks.

**Comment by mzagol** [comment]
Thank you for all the work on this plugin. There are 3 tickets regarding this issues; this one plus [this](https://github.com/marlonfan/coc-phpls/issues/48) and [this](https://github.com/marlonfan/coc-phpls/issues/82).

**Comment by reisnobre** [comment]
Still have this issue also

**Comment by mohammedabdoh** [comment]
No respond from the author on this issue.
